### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by iwqian** [xuperchain/pythonsdk#2]
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen      
    chunked=chunked)
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Program Files\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by fxsjy** [comment]
什么情况下可以复现，可否详细点。

**Comment by iwqian** [comment]
> 什么情况下可以复现，可否详细点。

修改demo.py中的IP和端口为真实的之后，直接运行demo.py就报错。
使用C#的SDK都没有问题，说明区块链的服务端是没有问题的。

**Comment by fxsjy** [comment]
@wangqian0628 , 需要启动http网关：
nohup ./xchain-httpgw &
因为pythonsdk是用的http+json协议，xchain-httpgw再把请求转发到xchain.
端口应该配置成xchain-httpgw网关的端口，而不是xchain节点的grpc端口。
