### ISSUE TITLE
pysdk.system_status()无法执行

### ISSUE THREAD

**Issue by KunmingS** [xuperchain/pythonsdk#6]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shikunming/miniconda3/lib/python3.9/site-packages/xuper/client.py", line 290, in system_status
    rsps_obj = json.loads(rsps.content)
  File "/Users/shikunming/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/shikunming/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/shikunming/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by KunmingS** [comment]
pysdk创建时用37301端口
